DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS VENDINGMACHINE;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS OWNERS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
	ID INT AUTO_INCREMENT,
    DL_ID VARCHAR(20),
    EMAIL VARCHAR(20),
    ADDRESS VARCHAR(20),
    NAME VARCHAR(20),
    CREDITS INT,
    PHONENUMBER VARCHAR(12),
    PRIMARY KEY(ID));

CREATE TABLE OWNERS (
	ID INT AUTO_INCREMENT,
    EMAIL VARCHAR(20),
    ADDRESS VARCHAR(20),
    PHONENUMBER VARCHAR(12),
    PRIMARY KEY(ID));

CREATE TABLE PRODUCTS (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(20),
    PRICE INT,
    PRIMARY KEY(ID));
    
    
CREATE TABLE VENDINGMACHINE (
    ID INT AUTO_INCREMENT,
    LOCATION VARCHAR(20),
    OWNER INT,
    STOCK INT,
    PRIMARY KEY(ID),
    FOREIGN KEY(OWNER) REFERENCES OWNERS(ID));

CREATE TABLE STOCK (
	ID INT AUTO_INCREMENT,
    VENDINGID INT,
    PRODUCTID INT,
    QUANTITY INT,
    SLOT INT,
    FOREIGN KEY(PRODUCTID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY(VENDINGID) REFERENCES VENDINGMACHINE(ID),
    PRIMARY KEY(ID));
    
    grant select on CUSTOMERS to public;
    grant select on VENDINGMACHINE to public;
    grant select on STOCK to public;
    grant select on OWNERS to public;
    grant select on PRODUCTS to public;

#---------------------------------- END TABLE CREATION -----------------------------------

insert into OWNERS (EMAIL, ADDRESS, PHONENUMBER)
values ("this@gmail.com", "6579 Laburnum St.", "2508265287");

insert into VENDINGMACHINE (LOCATION, OWNER, STOCK)
values ("McLeod", 1, 2);

insert into PRODUCTS (NAME, PRICE)
values ("Cigarettes", 1999);

insert into PRODUCTS (NAME, PRICE)
values ("Stella Artois", 1349);

insert into STOCK (VENDINGID, PRODUCTID, QUANTITY, SLOT)
values (1, 1, 5, 0);

insert into STOCK (VENDINGID, PRODUCTID, QUANTITY, SLOT)
values (1, 2, 10, 0);

insert into CUSTOMERS (DL_ID, EMAIL, ADDRESS, NAME, CREDITS, PHONENUMBER)
values("M01554195", "aidoraide@gmail.com", "6507 Maple St.", "Aidan Rosswood", 100000, "7788662529");

insert into CUSTOMERS (DL_ID, EMAIL, ADDRESS, NAME, CREDITS, PHONENUMBER)
values("M01984776", "kjm.ducks@gmail.com", "6579 Laburnum St.", "Kyle Martin", 200000, "2508265287");